services:
  php85:
    build: .
    container_name: php85
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/html
      - ./tests:/tests
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    tty: true
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
